@startuml
!include macros/crawl_items.puml
!include macros/download_items.puml

title Download command process


start
: deejay:pool:download <prodivder> - -start 1 - -end 10;
:Open [Provider] session;


if (Logged into The Game?) then (yes)
    CRAWL_ITEMS()
    if (--dry-run) then (yes)
    else (no)
        DOWNLOAD_ITEMS()
    endif
    :print summary;
else (no)
  stop
endif


stop

@enduml